apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casa-church-postgres-primary
  namespace: casa-church
spec:
  serviceName: casa-church-postgres-primary-headless
  replicas: 1
  selector:
    matchLabels:
      app: casa-church-postgres
      role: primary
  template:
    metadata:
      labels:
        app: casa-church-postgres
        role: primary
    spec:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: postgres
          image: bitnamilegacy/postgresql:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: master
            - name: POSTGRESQL_DATABASE
              value: casa_church
            - name: POSTGRESQL_USERNAME
              value: casachurchadmin
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casa-church-postgres-secret
                  key: postgres-password
            - name: POSTGRESQL_REPLICATION_USER
              value: repl_user
            - name: POSTGRESQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casa-church-postgres-secret
                  key: replication-password
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: postgres-primary-data
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-primary-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
