apiVersion: v1
kind: ConfigMap
metadata:
  name: casa-church-api-config
  namespace: casa-church
data:
  PORT: "3000"
  NODE_ENV: "production"
  FRONTEND_URL: "http://localhost"
  PGHOST: "postgreflex-casachurch.postgres.database.azure.com"
  PGPORT: "5432"
  PGDATABASE: "casa_church"
  PGUSER: "casachurchadmin"
  PGSSLMODE: "require"
  JWT_TOKEN_AUDIENCE: "casa-church-web"
  JWT_TOKEN_ISSUER: "casa-church-api"
  JWT_TTL: "3600"
