apiVersion: v1
kind: ResourceQuota
metadata:
  name: casa-church-quota
  namespace: casa-church
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "12"
