apiVersion: v1
kind: Secret
metadata:
  name: casa-church-api-secret
  namespace: casa-church
type: Opaque
stringData:
  PGPASSWORD: "replace-with-postgresql-password"
  JWT_SECRET: "replace-with-jwt-secret"
